import { NextResponse } from 'next/server'

import { createAdminClient } from '@/lib/supabase/admin'
import {
  asaasEventMarksPaid,
  buildAsaasWebhookEventId,
  extractAsaasChargeId,
  extractAsaasChargeStatus,
  extractAsaasEventType,
  isValidAsaasWebhookSecret,
} from '@/lib/integrations/asaas'
import {
  generateDistributionForPayment,
  loadFinanceSettingsAdmin,
  shouldAutoGenerateDistribution,
} from '@/lib/finance/distributions'
import { isUniqueViolation, toMessage } from '@/lib/finance/errors'
import { confirmRentCycleReceipt } from '@/lib/finance/rentCycles'

export const runtime = 'nodejs'

type JsonRecord = Record<string, unknown>

function toDateIso(value: unknown): string | null {
  const text = String(value || '').trim()
  if (!text) return null
  if (/^\d{4}-\d{2}-\d{2}$/.test(text)) return text
  const date = new Date(text)
  if (Number.isNaN(date.getTime())) return null
  return date.toISOString().slice(0, 10)
}

function toDateTimeIso(value: unknown): string | null {
  const text = String(value || '').trim()
  if (!text) return null
  const date = new Date(text)
  if (Number.isNaN(date.getTime())) return null
  return date.toISOString()
}

function toNumber(value: unknown): number {
  if (typeof value === 'number' && Number.isFinite(value)) return value
  if (typeof value === 'string' && value.trim()) {
    const parsed = Number(value)
    if (Number.isFinite(parsed)) return parsed
  }
  return 0
}

export async function POST(request: Request) {
  if (!isValidAsaasWebhookSecret(request, process.env.ASAAS_WEBHOOK_SECRET)) {
    return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 })
  }

  const payload = await request.json().catch(() => null)
  if (!payload || typeof payload !== 'object') {
    return NextResponse.json({ ok: false, error: 'Payload inválido.' }, { status: 400 })
  }

  const admin = createAdminClient()
  const eventId = buildAsaasWebhookEventId(payload)
  const eventType = extractAsaasEventType(payload)
  const nowIso = new Date().toISOString()

  let webhookEventId: string | null = null
  const insertEventRes = await admin
    .from('asaas_webhook_events')
    .insert({
      event_id: eventId,
      event_type: eventType,
      payload,
      status: 'received',
      received_at: nowIso,
    })
    .select('id, status')
    .maybeSingle()

  if (insertEventRes.error) {
    if (isUniqueViolation(insertEventRes.error)) {
      const existingRes = await admin
        .from('asaas_webhook_events')
        .select('id, status, processed_at')
        .eq('event_id', eventId)
        .maybeSingle()

      if (existingRes.data?.id && existingRes.data.status === 'processed') {
        return NextResponse.json({
          ok: true,
          status: 'duplicate',
          event_id: eventId,
          processed_at: existingRes.data.processed_at || null,
        })
      }
      webhookEventId = existingRes.data?.id ?? null
    } else {
      return NextResponse.json(
        { ok: false, error: insertEventRes.error.message || 'Erro ao registrar webhook.' },
        { status: 500 }
      )
    }
  } else {
    webhookEventId = insertEventRes.data?.id ?? null
  }

  const asaasChargeId = extractAsaasChargeId(payload)
  if (!asaasChargeId) {
    if (webhookEventId) {
      await admin
        .from('asaas_webhook_events')
        .update({
          status: 'failed',
          last_error: 'Evento sem payment_id/charge_id.',
          processed_at: nowIso,
        })
        .eq('id', webhookEventId)
    }
    return NextResponse.json({ ok: true, status: 'ignored', reason: 'missing_charge_id' }, { status: 202 })
  }

  const chargeRes = await admin
    .from('asaas_charges')
    .select('id, receivable_id, financial_account_id, asaas_charge_id, status')
    .eq('asaas_charge_id', asaasChargeId)
    .maybeSingle()

  if (chargeRes.error || !chargeRes.data) {
    if (webhookEventId) {
      await admin
        .from('asaas_webhook_events')
        .update({
          status: 'failed',
          last_error: toMessage(chargeRes.error, `Cobrança Asaas não encontrada para id ${asaasChargeId}.`),
          processed_at: nowIso,
        })
        .eq('id', webhookEventId)
    }
    return NextResponse.json({ ok: true, status: 'ignored', reason: 'charge_not_found' }, { status: 202 })
  }

  const charge = chargeRes.data as {
    id: string
    receivable_id: string
    financial_account_id: string
    asaas_charge_id: string
    status: string | null
  }

  const status = extractAsaasChargeStatus(payload) || charge.status || null
  const paymentNode = (payload as JsonRecord).payment as JsonRecord | undefined
  const pixQrCodeNode = paymentNode?.pixQrCode as JsonRecord | undefined
  const pixTransactionNode = paymentNode?.pixTransaction as JsonRecord | undefined
  const pixNode = paymentNode?.pix as JsonRecord | undefined
  const dueDate = toDateIso(paymentNode?.dueDate)
  const invoiceUrl = String(paymentNode?.invoiceUrl || '').trim() || null
  const bankSlipUrl = String(paymentNode?.bankSlipUrl || '').trim() || null
  const bankSlipPdf = String(paymentNode?.bankSlipUrlPdf || paymentNode?.bankSlipPdfUrl || '').trim() || null
  const pixPayload = String(
    pixQrCodeNode?.payload || pixTransactionNode?.payload || pixNode?.payload || ''
  ).trim()

  await admin
    .from('asaas_charges')
    .update({
      status,
      due_date: dueDate,
      invoice_url: invoiceUrl,
      bank_slip_url: bankSlipUrl,
      bank_slip_pdf: bankSlipPdf,
      pix_payload: pixPayload || null,
      payload,
    })
    .eq('id', charge.id)

  const marksPaid = asaasEventMarksPaid(eventType, status)
  if (!marksPaid) {
    await admin
      .from('receivables')
      .update({
        external_status: status,
      })
      .eq('id', charge.receivable_id)

    if (webhookEventId) {
      await admin
        .from('asaas_webhook_events')
        .update({ status: 'processed', processed_at: nowIso, last_error: null })
        .eq('id', webhookEventId)
    }

    return NextResponse.json({ ok: true, status: 'processed', payment_created: false })
  }

  const paidAtIso =
    toDateTimeIso(paymentNode?.clientPaymentDate) ||
    toDateTimeIso(paymentNode?.paymentDate) ||
    toDateTimeIso(paymentNode?.confirmedDate) ||
    nowIso

  await admin
    .from('receivables')
    .update({
      status: 'paid',
      amount_open: 0,
      paid_at: paidAtIso,
      external_status: status,
    })
    .eq('id', charge.receivable_id)

  const receivableContextRes = await admin
    .from('receivables')
    .select(
      'id, amount_total, amount_open, business_line_id, property_id, property_category_id, broker_user_id, proposal_payment_method_id, collection_method_id, origin_type, origin_id'
    )
    .eq('id', charge.receivable_id)
    .maybeSingle()

  const receivableContext = (receivableContextRes.data ?? null) as
    | {
        id: string
        amount_total: number | null
        amount_open: number | null
        business_line_id: string | null
        property_id: string | null
        property_category_id: string | null
        broker_user_id: string | null
        proposal_payment_method_id: string | null
        collection_method_id: string | null
        origin_type: string | null
        origin_id: string | null
      }
    | null

  const receivableOriginType = String(receivableContext?.origin_type || '').toLowerCase()
  const receivableOriginId = String(receivableContext?.origin_id || '').trim() || null
  const isRentCycleReceivable = receivableOriginType === 'deal_rent_cycle' && Boolean(receivableOriginId)

  const payloadAmount = Math.max(
    toNumber(paymentNode?.value) || toNumber(paymentNode?.netValue) || toNumber(paymentNode?.originalValue),
    0
  )
  const receivableAmountFallback = Math.max(
    toNumber(receivableContext?.amount_open) || toNumber(receivableContext?.amount_total),
    0
  )
  const paymentAmount = payloadAmount > 0 ? payloadAmount : receivableAmountFallback

  let paymentId: string | null = null
  const existingPaymentRes = await admin
    .from('payments')
    .select('id')
    .eq('direction', 'in')
    .eq('receivable_id', charge.receivable_id)
    .eq('external_provider', 'asaas')
    .eq('external_id', asaasChargeId)
    .maybeSingle()

  if (existingPaymentRes.data?.id) {
    paymentId = existingPaymentRes.data.id
    await admin
      .from('payments')
      .update({
        status: 'confirmed',
        amount: paymentAmount,
        paid_at: paidAtIso,
        financial_account_id: charge.financial_account_id,
        origin_type: 'asaas_charge',
        origin_id: charge.id,
        business_line_id: receivableContext?.business_line_id ?? null,
        property_id: receivableContext?.property_id ?? null,
        property_category_id: receivableContext?.property_category_id ?? null,
        broker_user_id: receivableContext?.broker_user_id ?? null,
        proposal_payment_method_id: receivableContext?.proposal_payment_method_id ?? null,
        collection_method_id: receivableContext?.collection_method_id ?? null,
        distribution_status: 'pending',
      })
      .eq('id', paymentId)
  } else {
    const insertedPaymentRes = await admin
      .from('payments')
      .insert({
        direction: 'in',
        receivable_id: charge.receivable_id,
        financial_account_id: charge.financial_account_id,
        amount: paymentAmount,
        paid_at: paidAtIso,
        status: 'confirmed',
        external_provider: 'asaas',
        external_id: asaasChargeId,
        origin_type: 'asaas_charge',
        origin_id: charge.id,
        business_line_id: receivableContext?.business_line_id ?? null,
        property_id: receivableContext?.property_id ?? null,
        property_category_id: receivableContext?.property_category_id ?? null,
        broker_user_id: receivableContext?.broker_user_id ?? null,
        proposal_payment_method_id: receivableContext?.proposal_payment_method_id ?? null,
        collection_method_id: receivableContext?.collection_method_id ?? null,
        distribution_status: 'pending',
      })
      .select('id')
      .maybeSingle()

    if (!insertedPaymentRes.error && insertedPaymentRes.data?.id) {
      paymentId = insertedPaymentRes.data.id
    }
  }

  if (paymentId) {
    const existingBankTxRes = await admin
      .from('bank_transactions')
      .select('id')
      .eq('external_provider', 'asaas')
      .eq('external_id', asaasChargeId)
      .eq('direction', 'in')
      .maybeSingle()

    if (!existingBankTxRes.data?.id) {
      await admin.from('bank_transactions').insert({
        financial_account_id: charge.financial_account_id,
        payment_id: paymentId,
        occurred_at: paidAtIso,
        direction: 'in',
        amount: paymentAmount,
        description: String(paymentNode?.description || `Cobrança Asaas ${asaasChargeId}`),
        reconciled: true,
        reconciled_at: paidAtIso,
        business_line_id: receivableContext?.business_line_id ?? null,
        property_id: receivableContext?.property_id ?? null,
        property_category_id: receivableContext?.property_category_id ?? null,
        broker_user_id: receivableContext?.broker_user_id ?? null,
        origin_type: 'asaas_charge',
        origin_id: charge.id,
        external_provider: 'asaas',
        external_id: asaasChargeId,
        metadata: {
          proposal_payment_method_id: receivableContext?.proposal_payment_method_id ?? null,
          collection_method_id: receivableContext?.collection_method_id ?? null,
        },
      })
    }
  }

  let rentCycleSync: { ok: boolean; cycleId?: string; error?: string } | null = null
  if (isRentCycleReceivable && receivableOriginId) {
    const rentCycleRes = await confirmRentCycleReceipt({
      cycleId: receivableOriginId,
      actorUserId: null,
    })
    rentCycleSync = rentCycleRes.ok
      ? { ok: true, cycleId: rentCycleRes.cycleId }
      : { ok: false, error: rentCycleRes.error }
  }

  if (webhookEventId) {
    await admin
      .from('asaas_webhook_events')
      .update({
        status: 'processed',
        processed_at: nowIso,
        last_error: rentCycleSync && !rentCycleSync.ok ? `rent_cycle_sync_failed: ${rentCycleSync.error}` : null,
      })
      .eq('id', webhookEventId)
  }

  let autoDistribution: { ok: boolean; error?: string; distributionId?: string } | null = null
  const skipAutoDistribution = receivableOriginType === 'deal_rent_cycle'
  if (paymentId && !skipAutoDistribution) {
    const settings = await loadFinanceSettingsAdmin()
    const shouldAuto = await shouldAutoGenerateDistribution({
      paymentId,
      settings,
    })
    if (shouldAuto) {
      const distributionResult = await generateDistributionForPayment({
        paymentId,
        actorUserId: settings?.updated_by ?? null,
      })
      autoDistribution = distributionResult.ok
        ? { ok: true, distributionId: distributionResult.distributionId }
        : { ok: false, error: distributionResult.error }
    }
  }

  return NextResponse.json({
    ok: true,
    status: 'processed',
    payment_id: paymentId,
    rent_cycle_sync: rentCycleSync,
    auto_distribution_skipped: skipAutoDistribution,
    auto_distribution: autoDistribution,
  })
}
